### ISSUE TITLE
the example runs itself, is it possible to rewrite the example with discrete steps?

### ISSUE THREAD

**Issue by dr-joe-wirth** [PenilCelis/Salmonella_Typhi_JINA#3]
thank you for providing an example, but it is difficult to follow because it runs itself. is it possible for you to provide an example where you break down each step, what you are doing at each step, and then run it as individual commands? this would be much easier for me to learn how to apply your workflow to real world data. as it stands now, the bash script you provide will only work on one set of input files.

for example, your readme might include the following sections within the example:
* installing the tool (already included)
* downloading the sequences (already included)
* running jellyfish
* running `bindash_block_sketch.pl`
* running `bindash_block_dist.pl`
* doing the next step (i do not understand what is happening in remainder of the code)

**Comment by dr-joe-wirth** [comment]
ok so i have been looking it over, and perhaps i misunderstood the bash script. it looks like it is the main wrapper that runs the pipeline.

can you please add instructions for how to use it? as it stands the command to run the workflow is not explained in any way:

```bash
bash ./typhi_JINA_pipeline.sh test_seqs/genome_list.txt test_seqs test_out 16 32
```

**Comment by PenilCelis** [comment]
I have incorporated your recommendations. Thank you very much.

**Comment by dr-joe-wirth** [comment]
you need to "merge the pull request" to actually incorporate them

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request#merging-a-pull-request
